version: '3.8'
services:
  mudah-monitor:
    build: .
    volumes:
      - ./data/listing.db:/app/data/listing.db
      - ./mudah-listing-monitor/.env:/app/mudah-listing-monitor/.env
      - ./data/searchUrls.json:/app/data/searchUrls.json
    restart: always